//#region USUÁRIO

export const USR_GET_PESSOA_LOGADA = 'USR_GET_PESSOA_LOGADA'
export const USR_SET_PESSOA_JA_LOGADA = 'USR_SET_PESSOA_JA_LOGADA'
export const USR_SET_ESTADO_INICIAL_USUARIO_LOGADO = 'USR_SET_ESTADO_INICIAL_USUARIO_LOGADO'
export const USR_GET_DADOS_EMPREGADO = 'USR_GET_DADOS_EMPREGADO'

//#endregion

//#region ROTAS / MENUS

export const ROT_GET_ROTAS_PERMITIDAS = 'ROT_GET_ROTAS_PERMITIDAS'
export const ROT_SET_ROTAS_PERMITIDAS = 'ROT_SET_ROTAS_PERMITIDAS'
export const ROT_SET_MENUS = 'ROT_SET_MENUS'

//#endregion
