//#region DEFAULT

export const DEFAULT_GET_ESTADOS_CIVIS = 'DEFAULT_GET_ESTADOS_CIVIS'
export const DEFAULT_GET_TIPOS_EMPREGADO = 'DEFAULT_GET_TIPOS_EMPREGADO'
export const DEFAULT_GET_RACAS = 'DEFAULT_GET_RACAS'
export const DEFAULT_GET_GRAUS_INSTRUCAO = 'DEFAULT_GET_GRAUS_INSTRUCAO'
export const DEFAULT_GET_GENEROS = 'DEFAULT_GET_GENEROS'
export const DEFAULT_GET_TIPOS_LOGRADOURO = 'DEFAULT_GET_TIPOS_LOGRADOURO'
export const DEFAULT_GET_CIDADES = 'DEFAULT_GET_CIDADES'
export const DEFAULT_GET_FORMAS_PAGAMENTO = 'DEFAULT_GET_FORMAS_PAGAMENTO'
export const DEFAULT_GET_BANCOS = 'DEFAULT_GET_BANCOS'
export const DEFAULT_GET_TIPOS_CONTA = 'DEFAULT_GET_TIPOS_CONTA'
export const DEFAULT_GET_UNIDADES_FEDERATIVAS = 'DEFAULT_GET_UNIDADES_FEDERATIVAS'
export const DEFAULT_GET_TIPOS_CERTIDAO = 'DEFAULT_GET_TIPOS_CERTIDAO'
export const DEFAULT_GET_TIPOS_ADMISSAO = 'DEFAULT_GET_TIPOS_ADMISSAO'
export const DEFAULT_GET_VINCULOS = 'DEFAULT_GET_VINCULOS'
export const DEFAULT_GET_CATEGORIAS = 'DEFAULT_GET_CATEGORIAS'
export const DEFAULT_GET_PARAMETROS_SALARIAL = 'DEFAULT_GET_PARAMETROS_SALARIAL'
export const DEFAULT_GET_TIPOS_PAGAMENTO = 'DEFAULT_GET_TIPOS_PAGAMENTO'
export const DEFAULT_GET_TIPOS_SALARIO = 'DEFAULT_GET_TIPOS_SALARIO'

//#endregion

//#endregion


//#endregion

//#region USUÁRIO

export const USR_GET_PESSOA_LOGADA = 'USR_GET_PESSOA_LOGADA'
export const USR_SET_PESSOA_JA_LOGADA = 'USR_SET_PESSOA_JA_LOGADA'
export const USR_SET_ESTADO_INICIAL_USUARIO_LOGADO = 'USR_SET_ESTADO_INICIAL_USUARIO_LOGADO'
export const USR_GET_CARGO_EMPREGADO = 'USR_GET_CARGO_EMPREGADO'

//#endregion

//#region ROTAS / MENUS

export const ROT_GET_ROTAS_PERMITIDAS = 'ROT_GET_ROTAS_PERMITIDAS'
export const ROT_SET_ROTAS_PERMITIDAS = 'ROT_SET_ROTAS_PERMITIDAS'
export const ROT_SET_MENUS = 'ROT_SET_MENUS'

//#endregion
